# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='intro',
            field=models.CharField(max_length=100, verbose_name='简介'),
        ),
    ]
