# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import extensions.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20170517_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='image',
            field=models.ImageField(default='collector/default.png', upload_to=extensions.modelutils.PathAndRename('collector/'), verbose_name='图片'),
        ),
    ]
