# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import extensions.modelutils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', extensions.modelutils.RandomFixedCharField(editable=False, max_length=16, unique=True, verbose_name='编号')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '文章管理',
                'verbose_name': '文章管理',
            },
        ),
    ]
