# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='intro',
            field=models.CharField(default='', max_length=128, verbose_name='简介'),
        ),
    ]
