# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import extensions.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='info/default.png', upload_to=extensions.modelutils.PathAndRename('info/'), verbose_name='图片'),
        ),
    ]
