# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import extensions.modelutils


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', extensions.modelutils.RandomFixedCharField(editable=False, max_length=8, unique=True, verbose_name='编号')),
                ('image', models.ImageField(default='info/default.png', upload_to=extensions.modelutils.PathAndRename('info/'), verbose_name='图片')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('intro', models.CharField(default='', max_length=128, verbose_name='简介')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '专栏管理',
                'verbose_name_plural': '专栏管理',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='info.Column', verbose_name='专栏'),
        ),
    ]
