# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 14:07
from __future__ import unicode_literals

from django.db import migrations
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20170615_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='content',
            field=simditor.fields.RichTextField(default='', verbose_name='内容'),
        ),
    ]
